### PR TITLE
Adding failover capability for vRO shim

### PR DESCRIPTION
**Pull request by tkopton**
As discussed with John and Alan via email.

### CODE REVIEW

**Comment by alanjcastonguay** [comment]
@tkopton are you planning to fix the failing tests?

**Comment by tkopton** [comment]
@alanjcastonguay Generally, yes. These is my very first try to contribute to a GitHub Python project / Travis etc. I suppose this is the reason:

E       UnboundLocalError: local variable 'r' referenced before assignment
loginsightwebhookdemo/__init__.py:243: UnboundLocalError

Let me check it. Thanks.

**Comment by alanjcastonguay** [comment]
This is not a good idea. You've modified `callapi` with extra arguments. Instead, modify the caller to iterate over a list (array) and call `callapi` multiple times, once with each url until it succeeds.

**Comment by tkopton** [comment]
As agreed, closing the request and changing the way how this feature might be implemented.

**Comment by johnddias** [comment]
Would it be better to push this back onto architecture of vRO?  The shim should not have to monitor the state of vRO in my opinion.  vRO should be built behind a LB in the case where availability is required.  If anything, a queue mechanism would be helpful for the shim in the event an endpoint is down or unavailable.

**Pull request closed without merging**
