### PR TITLE
Update CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by alanjcastonguay**
Correct path to repository in test setup instructions.

### CODE REVIEW

**Comment by alanjcastonguay** [comment]
Thanks for the catch, @tkopton

**Comment by alanjcastonguay** [comment]
There’s a flakey test in the master branch. It appears to be making a request to a google service and parsing the result. Can https://httpbin.org/ or a mock be used more reliably?

**Comment by vmw-loginsight** [comment]
Probably -- file a bug.

**Comment by alanjcastonguay** [comment]
Created issue #45

**Comment by alanjcastonguay** [comment]
Merge #46 and #47 then update this branch.

**Pull request merged**
